### ISSUE TITLE
Firefox mobile support please

### ISSUE THREAD

**Issue by pcause** [ChrisAntaki/disable-webrtc-firefox#1]
Looks like a GREAT addition to firefox, and thanks.  When I try to also add to my mobile it isn't in the addins.  Can you update the package to support firefox mobile

**Comment by ChrisAntaki** [comment]
Thanks for the heads up. I will look into adding Firefox Mobile support soon.

**Comment by ChrisAntaki** [comment]
Just submitted a new version with Firefox Mobile support: https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/?page=1#version-1.0.6

Thanks again for bringing this up.

**Comment by pcause** [comment]
Thanks so much.  Just installed.  One thing is that there is no menu item to enable/disable.  I can do it it add ons so that will work but when I tape the Android menu key there could be an item to toggle state.  Extensions like Self-destructing cookies or uBlock Origin add items for this purpose.

**Comment by ChrisAntaki** [comment]
Interesting, I will look into how they're doing that

Sent over the air

**Comment by ChrisAntaki** [comment]
Hey @pcause , I submitted an update just now which should add a menu item for mobile users
