### ISSUE TITLE
persist enabled webrtc

### ISSUE THREAD

**Issue by Konfekt** [ChrisAntaki/disable-webrtc-firefox#10]
After clicking the 'disable webrtc' icon to enable webrtc, and restarting firefox, then webrtc is disabled again. The only way to enable webrtc persistently is to disable this extension it seems.

(Because `ublock origin` blocks `webrtc` to some extent, and sites like airbnb do not work without webrtc, sometimes it's sufficient and more convenient to keep webrtc enabled by default. But the comfort of disabling it by the click of an icon is still appreciated.)

**Comment by ChrisAntaki** [comment]
Cool idea, @Konfekt. Though I'm afraid of catching users off guard. Some people are probably used to closing their browser with WebRTC enabled, and expect WebRTC to be disabled for their next session. Feel free to fork the addon though. :smile:

**Comment by Konfekt** [comment]
Ok, then the persistence of webrtc should be a preference that is disabled by default. Would that be possible ?

**Comment by ChrisAntaki** [comment]
Definitely, just uploaded a new version: https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/?page=1#version-1.0.12 :sunglasses:

**Comment by Konfekt** [comment]
Thanks!
