### ISSUE TITLE
Not compatible with e10s

### ISSUE THREAD

**Issue by rugk** [ChrisAntaki/disable-webrtc-firefox#11]
Is this add-on compatible with Electrolysis (e10s)? Electrolysis is the new architecture of Firefox and Mozilla already rolls out some stable Firefox versions with e10s enabled.

More information:
- https://arewee10syet.com/
- https://wiki.mozilla.org/Electrolysis

---

According to [ACL](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) this add-on is not compatible with e10s.

**Comment by ChrisAntaki** [comment]
Yes, this add-on is compatible with Electrolysis. 😄

![image](https://cloud.githubusercontent.com/assets/1216762/18358087/4ac4a43c-75a8-11e6-9fc9-267c58b12a2e.png)

Perhaps the ACL add-on is being overly cautious?

**Comment by ChrisAntaki** [comment]
Going to close this for now. Thanks for calling this out!

**Comment by rugk** [comment]
No, you're looking at the wrong position. Check it again and go to the add-ons pane (`about:addons`). The panel you show is just for reporting that it is working.
If you want to mark your add-on as compatible with e10s you have to edit your manifest file.

**Comment by ChrisAntaki** [comment]
Yes, that panel is used for reporting, and it also indicates whether multiprocess is enabled, in the lower right corner. Behind it is a page testing whether WebRTC is disabled. The plugin does appear to be working, with multiprocess enabled. 😄

Good to know about the manifest.json, I will look into that...

**Comment by ChrisAntaki** [comment]
Thanks again for bringing this up, @rugk! An update is on the way
