### ISSUE TITLE
NordVPN possible issue?

### ISSUE THREAD

**Issue by kevinmurphy777** [ChrisAntaki/disable-webrtc-firefox#18]
Problem is that I'm in Canada, and I am definitely connected to a US server (confirmed by both NordVPN and by IPleak.net)

BUT

http://whatismyipaddress.com/       ..........is shows my actual map location--which is in Canada.

Using Foxfire 50.1.0 "WebRTC is disabled" (green icon)

Not sure where the problem is? NordVPN is asking for screen shots of the above pages....

thanks,
kevin

**Comment by ChrisAntaki** [comment]
Hey @kevinmurphy777 - is there any chance your browser is allowing that page to access your geolocation? (https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation)

**Comment by kevinmurphy777** [comment]
webRTC is/was disabled, & geo.enabled in firefox was already set to false

Kevin

**Comment by ChrisAntaki** [comment]
I'd try with a different VPN, just to be sure.

**Comment by zeengo** [comment]
Make sure to disable IPv6 protocol, that usually is the case.

**Comment by Gitoffthelawn** [comment]
@zeengo Is your recommendation to disable IPv6 in the entire browser?  Can you provide a few details as to why disabling IPv6 will help?  Not questioning you... only trying to understand. :)

**Comment by zeengo** [comment]
If your ISP is providing you with IPv6, then it should be disabled as most VPN services are not covering the protocol yet. Leaving it enabled might be the reason why your location is exposed. 
Your location might also be displayed because you are using a WiFi access point mapped by Google or geo.enabled was reset as it might happen with an update (or sometimes without any reason at all (at least as far as I know))

**Comment by kevinmurphy777** [comment]
Thanks to all. a few questions, if I may:

1) zeengo said: "Your location might also be displayed because you are using a WiFi access point mapped by Google".... how do I stop the Google mapping issue specifically? geo.enabled in Firefox was already set to 'false' before this happens...

2) is IPv6 disabled at the operating system (Windows 10) or at the browser level?

3) what are the potential future bad consequences/disadvantages of disabling IPv6-- especially if I forget that I had made that change and it is needed by an ISP or some other technology in the future?

thanks to all

Kevin

**Comment by ChrisAntaki** [comment]
Thanks for the insights, @zeengo!

> what are the potential future bad consequences/disadvantages of disabling IPv6-- especially if I forget that I had made that change and it is needed by an ISP or some other technology in the future?

@kevinmurphy777 - You could just disable IPv6, until your VPN of choice starts covering the protocol. If that's going to take too long, switching VPN providers might be more ideal.

**Comment by kevinmurphy777** [comment]
done! thanks Chris... we will see how this goes..... always concerned that
I'll forget what I have "tweaked" in the past, and how (and what) to
reverse if things go sideways...

**Comment by ChrisAntaki** [comment]
Glad to help!

> always concerned that I'll forget what I have "tweaked" in the past, and how (and what) to reverse if things go sideways...

I totally understand that concern. It might help to create a calendar event, with a description like "Check if NordVPN supports IPv6 yet. For more details, check out @zeengo's points in this thread: https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/18#issuecomment-274847914"

**Comment by zeengo** [comment]
Most VPN providers are moving towards IPv6 support, some of them already did, however disabling the protocol will not cause any issues for at least a year or two. In general, IPv6 will be used once IPv4 addresses runs out, protocol provides multiple advantages, although at the moment I heard rumors that some security flaws are also detected and needs to be fixed before a global migration.
