### ISSUE TITLE
DNS is still leaking with WebRTC disabled

### ISSUE THREAD

**Issue by Jerry10101** [ChrisAntaki/disable-webrtc-firefox#19]
OS X 10.11.6
Firefox 53.0 (64 bit)
Disable WebRTC 1.0.16

Leaks are still showing up on: https://www.dnsleaktest.com/

I checked in about:config and I can see that media.peerconnection.enabled is set to "false", so I guess the plugin is doing its job. But I can't figure out why it's still leaking.

I'm trying this with Hoxx VPN, and I've seen in the reviews of your plugin that it's working with that add-on for other users.

Please help?

P.S. I'm kind of a noob, so I'm sorry if the solution is painfully obvious  :(

**Comment by ChrisAntaki** [comment]
Hey @Jerry10101 - I would recommend trying a paid VPN like [Private Internet Access](https://www.privateinternetaccess.com/pages/fftf). It costs $40 a year, and the link I provided donates some of the price to [Fight for the Future](https://www.fightforthefuture.org/). Personally, I haven't had much luck with free VPNs like Hoxx.

**Comment by ChrisAntaki** [comment]
If you're looking for a truly free VPN, I would recommend using [Tor](https://www.torproject.org/projects/torbrowser.html.en).

**Comment by Jerry10101** [comment]
Hi. Thanks for your response. I do use Tor as well and plan on going with either PIA or IVPN soon.

I was just trying to see if I could fix the leak with those VPN plugins/extensions as I would think it's more of a browser issue than the VPN itself (and some of the users of your plugin managed to make it work).

But maybe things changed after that and Firefox is leaking through something else.

**Comment by ChrisAntaki** [comment]
Perhaps the free VPN plugin used to work, but isn't fully compatible with newer versions of Firefox? I'd suggest opening a support ticket with the VPN developers. It sounds like the ball is in their court. 🏀
