### ISSUE TITLE
network.http.speculative-parallel-limit

### ISSUE THREAD

**Issue by urbie-mk2** [ChrisAntaki/disable-webrtc-firefox#2]
There's a new risky setting that got active with firefox 40:
network.http.speculative-parallel-limit
Maybe setting this to 0 could be added to the disable webrtc addon.
Webrtc could then evolve to an addon giving a stringent, sane and secure default. Although I am open for adding another addon beside Disable webrtc.

**Comment by ChrisAntaki** [comment]
Good call, I will create a new addon for this

**Comment by ChrisAntaki** [comment]
Just launched it 
https://github.com/ChrisAntaki/disable-speculative-pre-connections
https://addons.mozilla.org/en-US/firefox/addon/disable-speculative-pre-connec/
