### ISSUE TITLE
 how to disable Anonymizer

### ISSUE THREAD

**Issue by dumiduwpg** [ChrisAntaki/disable-webrtc-firefox#20]
Hi, 
Please tell me when I use a vpn whoer.net shows me  Anonymizer : vpn how to disable that ?
Thanks!

**Comment by ChrisAntaki** [comment]
That's a good question. They might just collect the IPs of popular VPNs. If that's the case, you could spin up your own VPN using OpenVPN on Google Cloud Platform. Here's a guide I just found, hope it helps: http://eugenioz.blogspot.com/2015/02/how-to-setup-vpn-on-google-cloud.html

**Comment by ChrisAntaki** [comment]
I'd recommend reaching out to your VPN with this question though. All my plugin is doing is disabling WebRTC. 😄
