### ISSUE TITLE
Please update to the new firefox addon standard.

### ISSUE THREAD

**Issue by nicholasmullikin** [ChrisAntaki/disable-webrtc-firefox#21]
There is more information about the new standard introduced in FF57 to keep add-on compatible [here](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct)

**Comment by ChrisAntaki** [comment]
Hey @nicholasmullikin, it looks like WebExtensions aren't allowed to change browser settings, so this addon can't be migrated. 😢 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Comparison_with_the_Add-on_SDK#Settings

**Comment by ChrisAntaki** [comment]
> Note that WebExtensions does not give you access to the browser's own preferences (that is, the preferences exposed in the SDK by preferences/service).

**Comment by ghost** [comment]
> it looks like WebExtensions aren't allowed to change browser settings, so this addon can't be migrated.

Not good, especially since this is a security addon.

**Comment by loganmarchione** [comment]
@ChrisAntaki, does [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1364975) not describe exactly what you need? It looks like the new setting is **peerConnectionEnabled** from [this page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network).

**Comment by ChrisAntaki** [comment]
Thanks for researching this, Logan! I'll join in on the bug page.

**Comment by ChrisAntaki** [comment]
Migration update has been submitted
