### ISSUE TITLE
Disable WebRTC on CEF

### ISSUE THREAD

**Issue by LassGobbeln** [ChrisAntaki/disable-webrtc-firefox#22]
Hey, I need to disable WebRTC on Chromium Embedded Framework 3, I have an important browser-simulating program but it's useless if my IP is being leaked. There is no way to install addons on CEF, it would be great if you could somehow help me fix this. On Firefox your addon works great, disables WebRTC completely. Maybe you can help me out on this one :)

**Comment by ChrisAntaki** [comment]
Hey, it looks like there might be some similar extensions for chrome already. I'd try checking out the market.

**Comment by LassGobbeln** [comment]
Sadly CEF doesn't have much to do with the basic Chrome, there are lots of WebRTC blockers for Chrome but CEF can only be configurated with code. I found some code to prevent IP leaking but it won't work. Anyways, thanks for your help!

**Comment by ChrisAntaki** [comment]
Yeah, sorry I couldn't help. It might be worth filling a ticket in that project asking for the feature. Who knows, maybe they could add a config option fairly easily. Good luck!
