### ISSUE TITLE
Clicking to disable disabling no longer works in 1.0.20

### ISSUE THREAD

**Issue by SchmyeBubbula** [ChrisAntaki/disable-webrtc-firefox#24]
Clicking little icon in toolbar (or whatever you call it) to disable disabling no longer works in 1.0.20.
Firefox 48.0.2 (latest Firefox supported in Mac Snow Leopard... and "You need to upgrade OS" is off-topic!).

**Comment by ChrisAntaki** [comment]
Hey @SchmyeBubbula, I just updated the plugin to only work with Firefox 55+. Sorry about the confusion, I didn't realize the AMO interface would keep defaulting to 48+.

**Comment by SchmyeBubbula** [comment]
Where can I obtain the last previous version that will still work in Firefox 48.0.2? Please add the link to your addons.mozilla.org page so we Snow Leopard holdouts can continue to use it. (It was working fine until the recent auto-update.)

**Comment by ChrisAntaki** [comment]
Here's a list of previous versions
https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/
