### ISSUE TITLE
Addons list Version 1.0.20 as compatiable with wrong FireFox version

### ISSUE THREAD

**Issue by FrustratedFireFoxUser** [ChrisAntaki/disable-webrtc-firefox#25]
Version 1.0.20 shows that it "Works with Firefox for Android 48.0 and later, Firefox 48.0 and later " yet Version 1.0.18 said "Works with Firefox for Android 55.0 and later, Firefox 55.0 and later" & "This release updates the addon to use the WebExtensions API."

This will cause problems for users of  ESR v 52 Firefox.

Should not Version 1.0.20 show "Works with Firefox for Android 55.0 and later, Firefox 55.0 and later" as it is supposedly a WebExtensions version?

**Comment by ChrisAntaki** [comment]
You're right, thanks for pointing that out! The listing has been updated.
