### ISSUE TITLE
msgsafe.io

### ISSUE THREAD

**Issue by Samuel6969** [ChrisAntaki/disable-webrtc-firefox#26]
Dear Sir,

I tried to go on https://www.msgsafe.io/ and I realized I could not access this website without disabling Webrtc. Would you tell me what is the problem with this website?

Many thanks
Samuel

**Comment by ChrisAntaki** [comment]
It looks like msgsafe.io uses WebRTC for its video and audio calls.

**Comment by ChrisAntaki** [comment]
If you trust the service, perhaps it makes sense to enable WebRTC while you use it? It's your call. You can quickly toggle WebRTC on/off by clicking the add-on's icon. Green = off, Red = on.
