### ISSUE TITLE
Addon doesn't work on Waterfox

### ISSUE THREAD

**Issue by Telmesomething** [ChrisAntaki/disable-webrtc-firefox#28]
I'd already tried preventing the WebRTC leak using "media.peerconnection.enabled = false" in  prefs, but it didn't work, so I tried using your addon instead. However, [whoer.net](https://whoer.net/#extended) still showed WebRTC as enabled. 

At the time, I was using the latest version of Waterfox and was connecting to the Web using my Android mobile as a hotspot. The latter was connected to the data packet I'd purchased from a Thai ISP called AIS. Here's the Wikipedia article on them: https://en.wikipedia.org/wiki/Advanced_Info_Service

Thailand requires registration to use any ISP, but restricts tourists to a specific SIM which enables the authorities to track users. The SIM expires automatically once the user leaves the country. That might be the reason why WebRTC continues to leak users' IP, but I'm not sure.

**Comment by ChrisAntaki** [comment]
Interesting, I haven't tried the addon with Waterfox. Is it possible they don't support the newer `media.peerconnection.enabled` preference? I saw they forked Firefox to keep compatibility with older extensions.

**Comment by JohanPirlouit** [comment]
Hi Chris,

I'm sorry to revive this old topic but it is just to confirm that your extension (in version 1.0.21) works fine with both Waterfox Classic (FF56-based, previously known as just Waterfox) and the new Waterfox Current (FF68-based). I used the [whoer.net](https://whoer.net/#extended) link previously provided by _Telmesomething_ to test it..

Probably it was the previous version of Waterfox that was based on FF52 that didn't support the newer 
`media.peerconnection.enabled` preference.

By the way, Waterfox Current already includes a `WebRTC peer connection` option in Menu -> Options -> Privacy & Security. But I don't know about its efficiency and consistency comparing to your Disable WebRTC...

Best regards,
Johan

**Comment by ChrisAntaki** [comment]
Hey Johan, glad to hear the extension is working in the newest Waterfox. I wouldn't be surprised if that `WebRTC peer connection` is changing the same setting as this plugin. If so, I would guess the only difference would be hopefully this plugin makes it easier to toggle the setting on/off
