### ISSUE TITLE
I need your old version extension

### ISSUE THREAD

**Issue by diephb** [ChrisAntaki/disable-webrtc-firefox#29]
Hello! I need old version for firefox, v1.0.11 but i i cant find it in addfirefox, cab you give me it?

**Comment by ChrisAntaki** [comment]
Hey buddy, does this work?
[disable_webrtc-1.0.1-fx.xpi.zip](https://github.com/ChrisAntaki/disable-webrtc-firefox/files/3943756/disable_webrtc-1.0.1-fx.xpi.zip)

**Comment by diephb** [comment]
Thank you very much! I will check it later

**Comment by diephb** [comment]
no, it dont work for firefox v30, have you got another?

**Comment by ChrisAntaki** [comment]
Sorry that's the oldest version pretty much

**Comment by diephb** [comment]
if i use new version for firefox v30, can it work? i want to try, but oldversion cant download new version disable webrtc, can you sent to me?

**Comment by ChrisAntaki** [comment]
Nope, it wouldn't work. The new version uses an API added in later versions
of Firefox. You could try disabling the webrtc settings using the Firefox
settings interface though

**Comment by ChrisAntaki** [comment]
Would this work for you?
https://whoer.net/blog/article/how-to-disable-webrtc-in-various-browsers/

**Comment by ChrisAntaki** [comment]
Sorry I couldn't help more!

**Comment by diephb** [comment]
Thank you! I find out 1.06 can work on firefox v30
