### ISSUE TITLE
License note missing in file

### ISSUE THREAD

**Issue by flyingzebras** [ChrisAntaki/disable-webrtc-firefox#3]
Can you please add this to /resources/happybonobo_disable_webrtc/lib/main.js

/\* This Source Code Form is subject to the terms of the Mozilla Public
- License, v. 2.0. If a copy of the MPL was not distributed with this
- file, You can obtain one at http://mozilla.org/MPL/2.0/. */

Please add license headers in the rest of your files for all of your work, and I will be glad to approve them in https://directory.fsf.org/wiki/Free_Software_Directory_talk:IceCat_extensions_%28proposed%29. Please confirm if you want to help us so I can have a look later.

**Comment by ChrisAntaki** [comment]
Cool, I'll add those license headers

**Comment by ChrisAntaki** [comment]
@flyingzebras License headers have been added to Disable Speculative Pre-connections, Disable Visited Links, and Disable WebRTC

**Comment by ChrisAntaki** [comment]
Should I resubmit these to AMO too?

**Comment by flyingzebras** [comment]
Yes, we only approve verified software.

**Comment by flyingzebras** [comment]
@ChrisAntaki Please also add a COPYING file in the root directory that holds a copy of the license too.

**Comment by ChrisAntaki** [comment]
@flyingzebras Just added a COPYING file to each project, recompiled with `jpm`, and submitted to AMO - hopefully they'll be approved in the next few days!

**Comment by flyingzebras** [comment]
@ChrisAntaki Thank you for helping us. I will have a new look when they are uploaded.

Consider to make an add-on which merge all your Disable \* extensions into one. I think that would be really nice as the users only need to install one add-on.

**Comment by flyingzebras** [comment]
@ChrisAntaki You can re-use code from https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/ for such project.

**Comment by flyingzebras** [comment]
@ChrisAntaki Actually I would suggest that you submit your privacy suggestion to  https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/. That would be even better. Can you please do that?

**Comment by ChrisAntaki** [comment]
Glad to help @flyingzebras - I'll have to pause on working on these for a bit

**Comment by flyingzebras** [comment]
I understand. Good luck.

**Comment by flyingzebras** [comment]
@ChrisAntaki I asked about this task in https://github.com/schomery/privacy-settings/issues/18

**Comment by flyingzebras** [comment]
@ChrisAntaki https://directory.fsf.org/wiki/IceCat/Disable_WebRTC and your other add-ons have MPL 2.0 added to as their license.
