### ISSUE TITLE
Feature request: show blocked counter

### ISSUE THREAD

**Issue by Talkless** [ChrisAntaki/disable-webrtc-firefox#30]
It would be nice to have a small counter (on top of addon icon), like uBlock Origin, or Privacy Badger has, to show blocked attempts to start up WebRTC on current site. Currently, addon does provide protection when going to ipleak.net, but there's no feedback that something actually happened.

**Comment by ChrisAntaki** [comment]
This would be sweet, but it would require the addon to do more than just changing a setting, it would actually have to be intercepting WebRTC attempts on every page, and I'd like to avoid injecting JS on every page if possible :)
