### ISSUE TITLE
Verssion 1.0.23 can't install on Waterfox Classic

### ISSUE THREAD

**Issue by JohanPirlouit** [ChrisAntaki/disable-webrtc-firefox#32]
Hi Chris,

I currently use Waterfox Classic (based on FF56) and Disable WebRTC 1.0.21 and I can't update to version 1.0.23.. And when I try to manually install it, I get this message:

> This add-on could not be installed because it appears to be corrupt.

So, for the moment, I stay with the 1.0.21 version...

By the way, the version 1.0.23 works fine with the new Waterfox Current (based on FF68).

Best regards,
Johan

**Comment by MeNeDaUnAl** [comment]
Greetings Chris,

I have exactly the same situation of Johan.

Moreover, I've checked that Disable WebRTC 1.0.23 doesn't work with Firefox 56 too (same error) while it works well with Firefox 75.
Maybe Disable WebRTC is now developed as a WebExtension, so it cannot work with Browsers based on pre-Quantum Firefox?

Many thanks.

**Comment by Avrution** [comment]
Also chiming in with the same issue

**Comment by ChrisAntaki** [comment]
Sorry to hear the addon isn't working with older versions of Firefox/Waterfox. You are right about the plugin being developed as a WebExtension, @MeNeDaUnAl. Mozilla pushed pretty hard to make extensions convert to the WebExtension format 
![image](https://user-images.githubusercontent.com/1216762/80521335-b886ac00-893f-11ea-9e94-6b125c46a48d.png)
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Extension_Packaging

**Comment by ChrisAntaki** [comment]
I can't commit to supporting those legacy versions of Firefox/Waterfox going forward. However, here is the XPI for version 1.0.21, I hope it's helpful:
[disable_webrtc-1.0.21-an+fx.xpi.zip](https://github.com/ChrisAntaki/disable-webrtc-firefox/files/4547687/disable_webrtc-1.0.21-an%2Bfx.xpi.zip)

If you need other version XPIs, just ask. I should be able to fetch them from AMO's archives.

**Comment by ChrisAntaki** [comment]
If anyone would like to fork this addon to support those legacy versions of ${element}Fox then this commit branch (https://github.com/ChrisAntaki/disable-webrtc-firefox/tree/46fb1bb5b46ba9831d454b302fe8734890aa051c) would be a good place to start, right before the conversion to WebExtension

Also here is the tool I used to package the extension back then
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tools/jpm

Can't promise it'll work though, seems like Mozilla really wanted to deprecate it

**Comment by MeNeDaUnAl** [comment]
Thanks for Your reply, Chris.
I understand well that You cannot support legacy versions; life goes forward, whether You like it or not.

I also know I should use a more updated browser but there are old addons I can't do without.
Anyway I'll have to do it, sooner or later, at least for my main browser:
luckily, I always use portable versions, so it's easy for me to switch from one version (or a browser) to another.

Best regards and take care.

**Comment by ChrisAntaki** [comment]
Thanks for understanding, I hope you find a newer browser you like!

**Comment by JohanPirlouit** [comment]
Hi Chris,

First, thank you for your answers!

But there is something that I don't understand: since the version 1.0.21 is already a WebExtension addon, why the 1.0.23 can't work? Are there some changes in the signing method required by Mozilla that could explain the issue with Waterfox Classic?

I just installed the extension again directly from the "version history " page at Mozilla.org ([https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/](https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/)) and installing the 1.0.21 still works great (but of course not the 1.0.23). And, it still ask for update ^^!

Maybe updating the addon description regarding the minimum FF version required (57 and not 55) would probably stop 1.0.21 from asking for update on Waterfox Classic ;-)..

(For those who don't know about Waterfox Classic: it is a fork of the last pre-Quantum Firefox with the latest Mozilla security patches backported and no Mozilla telemetry included. That's why I still use it, as long as its developer maintains it.)

Best regards,
Johan

**Comment by ChrisAntaki** [comment]
Hey Johan, I just updated the minimum versions to 57, is it working better for you now?

**Comment by JohanPirlouit** [comment]
Chris, YES, IT WORKS!!! :-D

Good job! No more update request, even by a manual update check... Big thanx for that ;-).. And I keep the 1.0.21 XPI file in case I need it.

Best regards,
Johan

**Comment by ChrisAntaki** [comment]
Glad to hear it!

**Comment by MeNeDaUnAl** [comment]
Hi everyone,

I confirm that it works for me too.
I already blocked update requests (on Waterfox Classic) through another addon, "Addon Update Checker", but I tried to disable the block and still there's no update request, neither automatic nor manual.

While on Waterfox Current (FF 68+ core), Disable WebRTC normally updates to 1.0.23.

Well done!

Greetings from Italy

**Comment by Avrution** [comment]
Odd - still corrupt for me.  The previous 1.0.21 now updates correctly from the page, but not the latest.

**Comment by JohanPirlouit** [comment]
> Odd - still corrupt for me. The previous 1.0.21 now updates correctly from the page, but not the latest.

@Avrution: it's a normal behaviour if you use WF Classic or any previous versions: Disable-webrtc 1.0.23 is not designed for FF before 57 and, as I think you know, WF Classic is based on FF 56 ;-).

The fix simply consists in preventing WF Classic from updating Disable-webrtc to 1.0.23 and keeping version 1.0.21, which is the last to be compatible with it. Thus, the extension manager no longer displays an "update available" message for Disable-webrtc if you already have the 1.0.21.

Best regards,
Johan

**Comment by Avrution** [comment]
Gotcha, for some reason I thought the fix made it work with WF - I do see now that the update option is gone.
