### ISSUE TITLE
Feature Request: allow-list for extensions which use WebRTC

### ISSUE THREAD

**Issue by johnhamelink** [ChrisAntaki/disable-webrtc-firefox#33]
Hi there,

I normally run Tor Project's [Snowflake extension](https://addons.mozilla.org/en-US/firefox/addon/torproject-snowflake/), which works over WebRTC. It would be nice to be able to allow Snowflake to use WebRTC, while blocking everything else.

**Comment by ChrisAntaki** [comment]
Thanks for the feature request, John. In my experience, the only safe way to disable WebRTC is by using browser-wide settings. This plugin used to disable WebRTC via embedding JS on every page. Some websites were able to run their JS before the plugin's though, by opening windows and iframes. This motivated me to switch to the browser-wide setting, which doesn't have an option for per-site blocking.

**Comment by johnhamelink** [comment]
Hi @ChrisAntaki I see - I'm not familiar with how modern browsers work, and I was working under the impression that other plugins would have a different API to the one used by websites, etc. I think I agree with you that Snowflake is probably not a good enough reason to open up a codepath that could be abused somehow. That's a shame, but thanks for your detailed reply nonetheless.

**Comment by ChrisAntaki** [comment]
You're welcome, thanks again for the FR
