### ISSUE TITLE
Do you have a privacy policy?

### ISSUE THREAD

**Issue by ghost** [ChrisAntaki/disable-webrtc-firefox#34]
If you have one could you please share a link?

**Comment by ChrisAntaki** [comment]
Hey Kevin, this addon doesn't have a privacy policy currently. I'll start writing a formal privacy policy in the coming weeks. I can write a brief policy now though. The plugin doesn't collect any user data. The only data it saves is the preference to disable or enable webrtc. That preference is saved locally on the user's device. I have received offers to "monetize" the plugin but I have zero interest in them.

**Comment by ChrisAntaki** [comment]
Hey @ktleary, I added a privacy policy to the README. I remembered the addon doesn't save anything across sessions, it just keeps a true/false variable in memory while it's running. I just wrote "This add-on collects nothing and sends nothing." for the privacy policy. 😂 - I hope that's clear? If it leaves ambiguity, I could write more

If I recall correctly, a previous version of this add-on did save the enable/disable state across sessions, but I and/or someone else was concerned people might forget they'd left WebRTC enabled after a video conference or something, so I just stopped saving the preference to be safe

**Comment by ghost** [comment]
Sounds good ... when I am recommending an add-on I usually make sure it has: a repo, a good license and a privacy policy and that was the only piece missing. You might want to add it to your add-on page at some point, but as far as I'm concerned its resolved. Thank you for a quick response.

**Comment by ChrisAntaki** [comment]
I'm glad you let me know 👍

**Comment by ChrisAntaki** [comment]
I just updated the addon page as well
https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/
