### ISSUE TITLE
Feature Request: whitelist URLs or individual tabs

### ISSUE THREAD

**Issue by internationils** [ChrisAntaki/disable-webrtc-firefox#35]
Hello, I seem to run into WebRTC required sites a little more often lately, and it would be great if the settings could be applied on a per-tab or per-site basis. Maybe this is not possible or sensible as in https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/33 ... but it would be useful. 
If it is not possible, I would suggest briefly documenting this in a paragraph on the code page as I would think that this issue will come up more and more with increasing online video conferences etc. Thanks!!

**Comment by ChrisAntaki** [comment]
I'm glad you called this out! Firefox can't disable WebRTC per-tab or per-window, the setting affects the entire browser. I added the last sentence to the README, and I hope this adds clarity
