### ISSUE TITLE
Re-enable addon after closing tab / window

### ISSUE THREAD

**Issue by daniel-j-h** [ChrisAntaki/disable-webrtc-firefox#36]
Similar to https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/35 it looks like we can not disable WebRTC on a tab by tab basis. But can we temporary disable WebRTC globally, and then have it re-enabled when the user closes the tab or closes the window?

The use case is as follows:
- by default I want to disable WebRTC
- but sometimes I need WebRTC e.g. for a half an hour call
- I'm a stupid human who then forgets to disable WebRTC after the call again leaving me exposed

If we could scope the WebRTC disabling to a tab / session concept, that wold be great. Is this technically possible?

**Comment by ChrisAntaki** [comment]
Hey Daniel! Sadly, Firefox won't let us scope WebRTC settings to a tab/session/window. That being said, if you quit Firefox, then the Disable WebRTC extension should reactivate when you boot Firefox up next

**Comment by daniel-j-h** [comment]
Would it be possible on have an on tab removed listener

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getCurrent
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onRemoved

and in there set the global WebRTC setting? :thinking: And then have not just a single button the user can click but a second button like "Disable until tab is closed" for the video call use case described above?

**Comment by UmBottesWillen** [comment]
I second this. If the addon could disable WebRTC automatically after the tab that was in the foreground when it got enabled is closed, that would help keep users safe.
