### ISSUE TITLE
Icon color meanings?

### ISSUE THREAD

**Issue by PSIG-dev** [ChrisAntaki/disable-webrtc-firefox#39]
Just a note that there is no explanation I could find in the read.me of whether green is ON (protected) and red is OFF or the other way around.  In-case anyone is assuming, like me.  ;-)  Else, a noted test function or test page would be handy as well.

**Comment by ChrisAntaki** [comment]
When you hover over the icon, this tooltip appears 
<img width="110" alt="image" src="https://user-images.githubusercontent.com/1216762/148694853-679b8ba7-91df-4738-ac11-f8132f6bcb99.png">
