### ISSUE TITLE
Add a method to ask the user for every connection

### ISSUE THREAD

**Issue by rugk** [ChrisAntaki/disable-webrtc-firefox#4]
In Firefox 42 [a feature was added](https://hacks.mozilla.org/2015/09/controlling-webrtc-peerconnections-with-an-extension/) which allows add-ons to get information if a web service wants to use WebRTC.
I think implementing this here would be a nice idea too, so you only have to answer a question if you want to use WebRTC and otherwise you have no privacy impact.

An example implementation was published [on GitHub](https://github.com/fippo/plumber).

**Comment by ChrisAntaki** [comment]
This is a cool idea. Hopefully the new `media.peerconnection.ice.default_address_only` feature will accomplish the same goal, more or less.
