### ISSUE TITLE
FF42+ allows finer grained configuration options

### ISSUE THREAD

**Issue by urbie-mk2** [ChrisAntaki/disable-webrtc-firefox#5]
With Firefox version 42 and up a new configuration is available which allows the user to return the default address without leaking the local ip: media.peerconnection.ice.default_address_only
- The default interface used for general routing is identified and only that address is used for candidate generation
- LAN IP addresses are not generated, the external IP address for that interface is (for a VPN, the exit portal of the VPN)
- If your router does not support 'hairpinning', a within-LAN call will end up being routed through an external TURN server
- NOT supported with e10s (only available in Nightly and DevEdition) yet (see bug 1194259)

Details: https://wiki.mozilla.org/Media/WebRTC/Privacy

**Comment by ChrisAntaki** [comment]
Nice, I'll look into this soon

**Comment by ChrisAntaki** [comment]
Just submitted a [new version](https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/?page=1#version-1.0.9) to AMO

**Comment by ChrisAntaki** [comment]
Hey @dbruenig , could you confirm the new version of the plugin is working for you? It's working for me, and properly showing my VPN's public IP and all. There's a user who's experiencing issues though, and I'm hoping it's not a flaw with the new setting or anything.

Thanks!

**Comment by ChrisAntaki** [comment]
We got it all sorted out. :sunglasses:
