### ISSUE TITLE
Public IP

### ISSUE THREAD

**Issue by WriteThis** [ChrisAntaki/disable-webrtc-firefox#6]
I'm only continuing to post here to HELP YOU learn about your mistake.  I have a working addon already so I don't really care if you ever admit that you are mistaken or not. 

> > Essentially, many of the WebRTC "Here are your IPs" test pages are outdated. They'll still claim >> to show your ISP's public IP, even if you're behind a VPN. If you have this addon installed though, >> they'll just see your VPN's public IP
> > 
> > LAN IP addresses are not generated, the external IP address for that interface is (for a VPN, the >> exit portal of the VPN)

Let's set up the environment to be sure that you fully understand what I'm saying.

1) I am using a VPN.  Firefox is routed through this VPN. Every normal "what is my ip" website shows the IP of the VPN only.

2) Using **your addon**, every website that checks for WebRTC IP leaks shows my ISP's public IP.  **This is the WebRTC leak that is supposed to be blocked**.

Despite what you claim or whatever Mozilla's site claims about this new option, it does not work as an WebRTC leak prevention.

**USE A VPN FOR YOURSELF TO VERIFY AND DON'T JUST RELY ON WHAT "SHOULD" HAPPEN ACCORDING TO SOMEONE ELSE**

You can have all the reviews and comments removed that you wish but it does not change the fact that your addon does not work, and people will obviously see that for themselves.

Here's the PROOF.

My VPN's IP from whatismyip.com
![vpnip](https://cloud.githubusercontent.com/assets/16733299/12372593/21bd214e-bc2c-11e5-9c68-b6aa96c79dc2.png)

Results of WebRTC leak test from https://diafygi.github.io/webrtc-ips/ with no addons enabled. Shows my lan ips and my ISP IP.
![rtc1](https://cloud.githubusercontent.com/assets/16733299/12372604/61ef4a6c-bc2c-11e5-828d-8dfdd682a1ca.png)

https://www.browserleaks.com/webrtc
![rtc2](https://cloud.githubusercontent.com/assets/16733299/12372616/ad6328f6-bc2c-11e5-9bde-15d41ed9abd7.png)

https://www.privacytools.io/webrtc.html
![rtc3](https://cloud.githubusercontent.com/assets/16733299/12372620/ce370e30-bc2c-11e5-8e1e-2460951bf936.png)

Everything the same, local ip and ISP ip are exposed, while on a VPN with no addons enabled.

The same tests, **with your addon enabled**
![t1](https://cloud.githubusercontent.com/assets/16733299/12372646/49f9ec36-bc2d-11e5-9987-83333f3bd9af.png)
![t2](https://cloud.githubusercontent.com/assets/16733299/12372648/4a0e6ee0-bc2d-11e5-969e-d57bda342e95.png)
![t3](https://cloud.githubusercontent.com/assets/16733299/12372647/4a0c01d2-bc2d-11e5-99a8-5bb7bad5c34a.png)

This shows, with absolute proof, that your addon does not work as it should. WebRTC leak is to block your real public ip from being exposed through a VPN.

Same tests, with your addon disabled, and WebRTC Control addon enabled.
![r1](https://cloud.githubusercontent.com/assets/16733299/12372664/8c3db406-bc2d-11e5-9c3a-fb749d9194e7.png)
![r2](https://cloud.githubusercontent.com/assets/16733299/12372665/8c77c448-bc2d-11e5-976a-e538da655541.png)
![r3](https://cloud.githubusercontent.com/assets/16733299/12372666/8c873e46-bc2d-11e5-9b00-e5b7e60006c6.png)

Works as it should to prevent public IP exposure through a VPN.

Please stop trying to convince me, or yourself, that your addon is working as it should. As I said before, if you think this is correct then change your name to "WebRTC Publically Identifiable IP Leaker".  

I have shown you with 100% absolute proof that your addon does not work.  Blocking your LAN IP's from being exposed is not the important part of the WebRTC leak.

Since you are a fan of posting search terms in some way to validate anything, here's one for you.  Read the first few sites that come up.

https://duckduckgo.com/?q=webrtc+security+flaw

> > "VPN users are facing a massive security flaw as websites can easily see their home IP-addresses >>through WebRTC."
> > 
> > "security researchers revealed a massive security flaw that enables website owner to easily see >>the real IP addresses of users through WebRTC, even if they are using a VPN"

If you still want to claim that any of these test sites are outdated and that would somehow make any difference --- the fact that the public ISP IP is being exposed is the only issue at hand.  It doesn't matter how the leak is tested or against what version of webrtc implementation it is tested against.. exposing the public ip is a failure.  If Mozilla wants to claim 

for what it's worth, just playing with the settings real quick

media.peerconnection.enabled = false; no webrtc leak
or
media.peerconnection.ice.default_address_only = true; hides lan ip but exposes public ip
or
media.peerconnection.ice.relay_only = true; hides all ips, no webrtc leak
but may still have exposure against a new detection method that these sites do not test for. according to mozilla's page

> > NOTE: does not hide your external IP address from the TURN server itself (see >> use_document_iceservers and default_iceservers to restrict to a TURN of your choice). 

Ultimately, the only way to be sure there is no IP leak is to disable WebRTC completely.

**Comment by ChrisAntaki** [comment]
Thanks for making an issue. I hope we can come to an agreement on this. :)

> the fact that the public ISP IP is being exposed is the only issue at hand

Sure, let's discuss just the ISP IP leakage.

> media.peerconnection.ice.default_address_only = true; hides lan ip but exposes public ip

This setting is what the plugin now uses.

So here's what I think leads to you and I having different opinions here. When visiting these pages with a VPN active, and the Secure WebRTC plugin enabled in Firefox...

https://www.privacytools.io/webrtc.html
https://www.browserleaks.com/webrtc
https://diafygi.github.io/webrtc-ips/

I'm just seeing the VPN's public IP. But you're seeing your ISP's public IP, you're saying?

When you visit those pages with the plugin disabled, but the VPN still active, wouldn't you be seeing two different public IPs? Because when I visit the pages in Chrome, or in Firefox with the plugin disabled, but with the VPN still active, I'm seeing two public IPs there. One from my ISP, one from my VPN.

Cheers,
Chris

**Comment by WriteThis** [comment]
I just tested something else, so I'll admit that my setup might be slightly unique in the way I am connecting to the VPN; but not so unique that it should make a major difference.  Perhaps this is a different issue that needs to be addressed.

If I use the OpenVPN client then it appears your addon works as expected, I see the VPN IP only.

The way I was connecting, where your addon was not working, was through an SSH tunnel to the VPN.  I was using this method, essentially as a proxy, only for Firefox and not for all my internet traffic.

The other WebRTC addon works to block exposure of the ISP IP even through the SSH tunnel, perhaps by completely disabling WebRTC.  But this new option that Mozilla is providing, then, does not work as expected if using an SSH tunnel, and by extension, a proxy.

**Comment by JukkT** [comment]
Guys I'm not going to take a part for these specifics you are talking about, but for me this add on "Secure Webrtc for android" has being working perfectly until now when firefox totally disabled this add on withouth any warning. It happened last night and after that it has not been able to turn it on in my android firefox. I even tried to uninstal it and re instal older version wich worked perfectly for me but firefox android totally refuses to instal/turn on already installed add ons. This is very bad thing for the trustworthy of firefox. There should not be any forced autoupdate on firefox for android neither to its addons. Now some blocking of addons and possible ampering of addons directly effects everyone using hem immediately. People should have perfect control to use their addons (maby outdated ones even but still perf thrustworthy for their usage. Now peoples IPs are leaked although they think they are safe. I already gave feedback to Mozilla firefox team.

**Comment by ChrisAntaki** [comment]
> The way I was connecting, where your addon was not working, was through an SSH tunnel to the VPN. I was using this method, essentially as a proxy, only for Firefox and not for all my internet traffic.

Wow, interesting. Thanks for digging into this. I'll revert the changes to the plugin. Could you tell me how to replicate the SSH tunnel set up, just so I could confirm?

**Comment by ChrisAntaki** [comment]
> Guys I'm not going to take a part for these specifics you are talking about, but for me this add on "Secure Webrtc for android" has being working perfectly until now when firefox totally disabled this add on withouth any warning.

Thanks for pointing this out, looks like the same thing has happened on my phone.

> I already gave feedback to Mozilla firefox team.

Good call.

**Comment by ChrisAntaki** [comment]
I just pushed a new version which should fix both of your concerns. Thank you both _very much_ for bringing these issues up. Sorry for not catching them sooner.

https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/?page=1#version-1.0.11
