### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by spongessuck** [ChrisAntaki/disable-webrtc-firefox#7]
I do web development and utilize WebRTC in my applications.

It'd be nice to be able to whitelist a domain so that I can keep the add-on active and avoid having to turn it on and off when I need to test/use my applications.

**Comment by ChrisAntaki** [comment]
I'd love to add that feature, but WebRTC can only _safely_ be disabled browser wide.

**Comment by spongessuck** [comment]
Bummer. Thanks anyway!

**Comment by ChrisAntaki** [comment]
Thanks for bringing it up - I'll keep my eye out for upgrades from Mozilla.
