### ISSUE TITLE
airbnb.com broken

### ISSUE THREAD

**Issue by davidhedlund** [ChrisAntaki/disable-webrtc-firefox#9]
Learned from [Fat-Free](https://addons.mozilla.org/en-US/firefox/addon/fat-free-firefox/) Fox documentation:

> WebRTC Private IP Address Leak: Note that enabling this option will only block private IP address leak due to WebRTC. It will not disable WebRTC completely. Firefox Hello would still be usable as before.

Airbnb can not be used with your add-on (no animation on the main page on aribnb.com, defunct search filters, etc), but Airbnb can be used with Fat-Free Firefox ("Block private IP address leak due to WebRTC (applicable for Firefox 42 and above)" enabled).

**Comment by ChrisAntaki** [comment]
Hey @davidhedlund , sounds like Fat-Free Fox might be using the `media.peerconnection.ice.default_address_only` setting, instead of disabling WebRTC completely. For a span of time, this plugin actually switched to that setting too. Some users pointed out the new setting actually doesn't block private IP address leaks for some VPN configurations. After that I switched it back, not wanting to endanger any of the users.

**Comment by davidhedlund** [comment]
@ChrisAntaki Can you please state that on AMO?

**Comment by ChrisAntaki** [comment]
Good call, just added a note to the description!

**Comment by davidhedlund** [comment]
@ChrisAntaki Thanks.

I quoted that in http://directory.fsf.org/wiki/Free_Software_Directory:IceCat_extensions_%28proposed%29

>  WebRTC exposes your internal network IP(s), without user interaction. Review note: This add-on will disable WebRTC fully, required by some VPN services. If you are not benind a VPN you will benefint from only partial disable WebRTC as learned from Fat-Free Fox documentation: WebRTC Private IP Address Leak: Note that enabling this option will only block private IP address leak due to WebRTC. It will not disable WebRTC completely. Firefox Hello would still be usable as before. Airbnb can not be used with your add-on (no animation on the main page on aribnb.com, defunct search filters, etc), but Airbnb can be used with Fat-Free Firefox ("Block private IP address leak due to WebRTC (applicable for Firefox 42 and above)" enabled). - https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/9

**Comment by ChrisAntaki** [comment]
Glad to help, David

**Comment by ChrisAntaki** [comment]
e

**Comment by davidhedlund** [comment]
@ChrisAntaki Can you please also state that Firefox Hello, and all websites that are built on WebRTC (Airbnb, car2Go, UberConference, etc) will stop working with Disable WebRTC.

**Comment by Gitoffthelawn** [comment]
@ChrisAntaki wrote:

> Hey @davidhedlund , sounds like Fat-Free Fox might be using the `media.peerconnection.ice.default_address_only setting`, instead of disabling WebRTC completely. For a span of time, this plugin actually switched to that setting too. Some users pointed out the new setting actually doesn't block private IP address leaks for some VPN configurations.

Can you provide more details into that discovery?

**Comment by ChrisAntaki** [comment]
Hey @Gitoffthelawn, that's a good question.

@WriteThis, would you be able to tell us more about the SSH tunnel method you were using, that led to issues with the `media.peerconnection.ice.default_address_only` setting?

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by Gitoffthelawn** [comment]
@davidhedlund wrote:

> Can you please also state Disable WebRTC will disable Firefox Hello, and all websites that are built on WebRTC (Airbnb, car2Go, UberConference, etc) from working.

Hi David, you mentioned those websites being built on WebRTC.  The websites definitely break without WebRTC, and I'm trying to understand why non-WebRTC functions break on those sites when WebRTC is disabled.

From what I have concluded so far, it appears to be a bug in one of the third-party libraries that those sites call.  When WebRTC is disabled, the libraries fail in an ugly way.  In theory, if they fixed those libraries, things should work without WebRTC.

Have you performed any research into this?  Your statement that the sites are "built on WebRTC" makes me think maybe you've completed more research than myself.  Either that, or you were just using those words as a shorthand to mean "things break if WebRTC is disabled". :-)

**Comment by davidhedlund** [comment]
@Gitoffthelawn Thank you for pointing this out.

>Have you performed any research into this? Your statement that the sites are "built on WebRTC" makes me think maybe you've completed more research than myself.

I don't know more than what I [commented earlier](https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/9#issue-165942800) in this post:
>Airbnb can not be used with your add-on (no animation on the main page on aribnb.com, defunct search filters, etc), but Airbnb can be used with Fat-Free Firefox ("Block private IP address leak due to WebRTC (applicable for Firefox 42 and above)" enabled).

**Comment by davidhedlund** [comment]
@ChrisAntaki Can you please respond to my [earlier comment](https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/9#issuecomment-233159167)?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ChrisAntaki** [comment]
Hey @davidhedlund, could you tell me more about what's breaking on AirBnB?

**Comment by davidhedlund** [comment]
@ChrisAntaki See this [comment](https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/9#issue-165942800) in this post:
>Airbnb can not be used with your add-on (no animation on the main page on aribnb.com, defunct search filters, etc), but Airbnb can be used with Fat-Free Firefox ("Block private IP address leak due to WebRTC (applicable for Firefox 42 and above)" enabled).

**Comment by davidhedlund** [comment]
@ChrisAntaki Can you please re-open this issue?

**Comment by ChrisAntaki** [comment]
@davidhedlund, are you still seeing the issues with Firefox 49? If so, could you write some steps to reproduce the issue? Just now, I wasn't able to.

**Comment by davidhedlund** [comment]
[mylabel:question](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aquestion%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by stanlane** [comment]
Has this been fixed?

**Comment by ChrisAntaki** [comment]
Wasn't able to reproduce the issue...

**Comment by flyingzebras** [comment]
@ChrisAntaki Is davidhedlund blocked from commenting?

**Comment by ChrisAntaki** [comment]
Relevant:
https://github.com/davidhedlund/github/issues/3
